# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('utln', models.CharField(max_length=10, unique=True)),
                ('manager_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_initial', models.CharField(max_length=1)),
                ('utln', models.CharField(max_length=10, unique=True)),
                ('student_type', models.CharField(max_length=20)),
                ('jumbocash_id', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('school', models.CharField(max_length=30)),
                ('class_year', models.IntegerField()),
                ('barcode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_created_by', to='cardcontrol.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('building_name', models.CharField(max_length=120)),
                ('door_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_created_by', to='cardcontrol.Account')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_modified_by', to='cardcontrol.Account')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='doors',
            field=models.ManyToManyField(to='cardcontrol.Door'),
        ),
        migrations.AddField(
            model_name='card',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_modified_by', to='cardcontrol.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='door',
            unique_together=set([('address', 'building_name', 'door_name')]),
        ),
    ]
