# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardcontrol', '0002_remove_accounts_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Ids',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Doors',
            new_name='Door',
        ),
    ]
